version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  backend:
    build: ./backend
    environment:
      - PORT=3001
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=llama3
      # If you deploy frontend separately, set FRONTEND_ORIGIN
      # - FRONTEND_ORIGIN=https://your-frontend-domain.com
    ports:
      - "3001:3001"
    depends_on:
      - ollama
    restart: unless-stopped

  frontend:
    build: .
    ports:
      - "5174:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  ollama_data:
